# Generated by Django 4.0.5 on 2022-07-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_subplan_highlight_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subplanfeatures',
            name='subplan',
        ),
        migrations.AddField(
            model_name='subplanfeatures',
            name='subplan',
            field=models.ManyToManyField(to='main.subplan'),
        ),
    ]
